services:
  - type: web
    name: email-assistant
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn email_assistant.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.6
    disk:
      name: data
      mountPath: /data
      sizeGB: 1